export const OSU_CS_PLAN = [
  // ----------------- Lower-division core -----------------
  {
    code: "CS 1113",
    name: "Computer Science I",
    prereqs: [],
    category: "core-lower",
    tags: ["intro", "programming"],
  },
  {
    code: "CS 2133",
    name: "Computer Science II",
    prereqs: ["CS 1113"],
    category: "core-lower",
    tags: ["programming", "data-structures"],
  },
  // Support / math / gen-ed courses used in this demo profile
{
  code: "MATH 1513",
  name: "College Algebra",
  prereqs: [],
  category: "support",
  tags: ["math"],
},
{
  code: "ENGL 1113",
  name: "Freshman Composition I",
  prereqs: [],
  category: "gen-ed",
  tags: ["writing"],
},
{
  code: "POLS 1113",
  name: "American Government",
  prereqs: [],
  category: "gen-ed",
  tags: ["civics"],
},
{
  code: "CS 2114",
  name: "Object-Oriented Programming",
  prereqs: ["CS 1113"],
  category: "core-lower",
  tags: ["programming", "oop"],
},
{
  code: "MATH 2144",
  name: "Calculus I",
  prereqs: ["MATH 1513"],
  category: "support",
  tags: ["math"],
},
{
  code: "PHYS 2014",
  name: "General Physics I",
  prereqs: ["MATH 1513"],
  category: "support",
  tags: ["physics", "math"],
},
{
  code: "STAT 2013",
  name: "Elements of Statistics",
  prereqs: ["MATH 1513"],
  category: "support",
  tags: ["math", "statistics"],
},
{
  code: "CS 3000",
  name: "Special Topics: Project Lab",
  prereqs: ["CS 2133"],
  category: "elective",
  tags: ["project", "lab"],
},
{
  code: "HIST 1103",
  name: "Survey of American History",
  prereqs: [],
  category: "gen-ed",
  tags: ["history"],
},
{
  code: "CS 2253",
  name: "Discrete Structures",
  prereqs: ["MATH 1513"],
  category: "core-lower",
  tags: ["math", "discrete"],
},
{
  code: "SPCH 2713",
  name: "Intro to Speech Communication",
  prereqs: [],
  category: "gen-ed",
  tags: ["communication"],
},
{
  code: "UNIV 1111",
  name: "First-Year Seminar",
  prereqs: [],
  category: "gen-ed",
  tags: ["orientation"],
},
{
  code: "CS 0001",
  name: "Orientation to Computing",
  prereqs: [],
  category: "support",
  tags: ["orientation"],
},


  // ----------------- Major CS requirements -----------------
  {
    code: "CS 3353",
    name: "Data Structures and Algorithm Analysis I",
    prereqs: ["CS 2133"],
    category: "core-upper",
    tags: ["algorithms", "theory", "data-structures"],
  },
  {
    code: "CS 3363",
    name: "Organization of Programming Languages",
    prereqs: ["CS 2133"],
    category: "core-upper",
    tags: ["languages", "theory"],
  },
  {
    code: "CS 3443",
    name: "Computer Systems",
    prereqs: ["CS 2133"],
    category: "core-upper",
    tags: ["systems", "hardware"],
  },
  {
    code: "CS 3613",
    name: "Theoretical Foundations of Computing",
    prereqs: ["CS 3353", "CS 3653"],
    category: "core-upper",
    tags: ["theory", "math-heavy"],
  },
  {
    code: "CS 3653",
    name: "Discrete Mathematics for Computer Science",
    prereqs: [],
    category: "core-upper",
    tags: ["math", "discrete", "theory"],
  },
  {
    code: "CS 4243",
    name: "Introduction to Computer Security",
    prereqs: ["CS 3443"],
    category: "core-upper",
    tags: ["security", "systems"],
  },
  {
    code: "CS 4273",
    name: "Software Engineering",
    prereqs: ["CS 2133", "CS 3653", "CS 3443"],
    category: "core-upper",
    tags: ["software-engineering", "project", "team"],
  },
  {
    code: "CS 4283",
    name: "Computer Networks",
    prereqs: ["CS 2133", "CS 3443"],
    category: "core-upper",
    tags: ["networks", "systems"],
  },
  {
    code: "CS 4323",
    name: "Design and Implementation of Operating Systems I",
    prereqs: ["CS 3443"],
    category: "core-upper",
    tags: ["systems", "os"],
  },
  {
    code: "CS 4433",
    name: "Introduction to Database Systems",
    prereqs: ["CS 2133"],
    category: "core-upper",
    tags: ["databases", "data"],
  },
  {
    code: "CS 4883",
    name: "Social Issues in Computing",
    prereqs: [],
    category: "core-upper",
    tags: ["ethics", "society"],
  },
  {
    code: "CS 4523",
    name: "Cloud Computing and Distributed Systems",
    prereqs: ["CS 3353", "CS 3443"],
    category: "core-upper",
    tags: ["cloud", "systems", "project"],
  },
  {
    code: "CS 4983",
    name: "Senior Capstone Project",
    prereqs: ["CS 4273"],
    category: "core-upper",
    tags: ["capstone", "project", "team"],
  },

  // ----------------- CS electives (from catalog list) -----------------
  {
    code: "CS 2351",
    name: "Unix Programming",
    prereqs: ["CS 1113"],
    category: "elective",
    tags: ["unix", "tools", "systems"],
  },
  {
    code: "CS 2433",
    name: "C/C++ Programming",
    prereqs: ["CS 1113"],
    category: "elective",
    tags: ["systems", "low-level", "language"],
  },
  {
    code: "CS 3030",
    name: "Industrial Practice in Computer Science",
    prereqs: ["CS 3443"],
    category: "elective",
    tags: ["internship", "industry", "project"],
  },
  {
    code: "CS 3570",
    name: "Special Problems in Computer Science",
    prereqs: [],
    category: "elective",
    tags: ["special-topics", "project"],
  },
  {
    code: "CS 4143",
    name: "Computer Graphics",
    prereqs: ["CS 3353"],
    category: "elective",
    tags: ["graphics", "visual"],
  },
  {
    code: "CS 4153",
    name: "Mobile Applications Development",
    prereqs: ["CS 2133"],
    category: "elective",
    tags: ["mobile", "apps", "project", "ui"],
  },
  {
    code: "CS 4173",
    name: "Video Game Development",
    prereqs: ["CS 2133", "CS 2433"],
    category: "elective",
    tags: ["games", "graphics", "visual", "project"],
  },
  {
    code: "CS 4183",
    name: "Video Game Design",
    prereqs: ["CS 2133", "CS 2433"],
    category: "elective",
    tags: ["games", "graphics", "visual", "project"],
  },
  {
    code: "CS 4373",
    name: "Agile Software Development",
    prereqs: ["CS 4273"],
    category: "elective",
    tags: ["software-engineering", "project", "team"],
  },
  {
    code: "CS 4483",
    name: "Network Security and Defense",
    prereqs: ["CS 3443", "CS 4243", "CS 4283"],
    category: "elective",
    tags: ["security", "networks", "advanced"],
  },
  {
    code: "CS 4513",
    name: "Introduction to Numerical Analysis",
    prereqs: ["CS 3353"],
    category: "elective",
    tags: ["math-heavy", "numerical"],
  },
  {
    code: "CS 4570",
    name: "Special Topics in Computing / Network Attack Security",
    prereqs: ["CS 3443", "CS 4243", "CS 4283"],
    category: "elective",
    tags: ["security", "special-topics"],
  },
  {
    code: "CS 4623",
    name: "Introduction to Cyber Physical Systems",
    prereqs: ["CS 3443"],
    category: "elective",
    tags: ["embedded", "systems"],
  },
  {
    code: "CS 4743",
    name: "Extended Reality",
    prereqs: ["CS 3353"],
    category: "elective",
    tags: ["xr", "graphics", "visual"],
  },
  {
    code: "CS 4783",
    name: "Machine Learning",
    prereqs: ["CS 3353"],
    category: "elective",
    tags: ["ai-ml", "math-heavy", "data"],
  },
  {
    code: "CS 4793",
    name: "Artificial Intelligence",
    prereqs: ["CS 3353"],
    category: "elective",
    tags: ["ai-ml", "theory", "data"],
  },
  {
    code: "CS 4993",
    name: "Senior Honors Project",
    prereqs: ["CS 4273"],
    category: "elective",
    tags: ["honors", "project", "team"],
  },
];

// convenience map for lookup
export const CODE_TO_COURSE = new Map(OSU_CS_PLAN.map((c) => [c.code, c]));

